### ISSUE TITLE
Led borad red color bias

### ISSUE THREAD

**Issue by BenjaminAlvis** [awtrix/AWTRIX2.0-Controller#10]
my led board will displayed pink when it set up with(255,255,255)
how could I set a red bias in somewhere of the controller code?
thx : )

**Comment by donnerruebe** [comment]
you can use the code from this Example: https://github.com/FastLED/FastLED/blob/master/examples/ColorTemperature/ColorTemperature.ino
it even should be possible to use Hex-Colors as the docs say here: http://fastled.io/docs/3.1/group___color_enums.html
