### ISSUE TITLE
Why the random MQTT-ID?

### ISSUE THREAD

**Issue by donnerruebe** [awtrix/AWTRIX2.0-Controller#12]
Around Line 240 you generate a random ID for the MQTT-Connection. Why don't you use the ESP.getChipId() for the ID, so you can manage multiple AWTRIXes together and seperate, by pushing them in another subscription?

So far GREAT JOB and many THANKS.

**Comment by Blueforcer** [comment]
AWTRIX Host is not designed for multiple matrices with different contenr, therefore its only possible to run multiple matrices with the same content. So you need different IDs. With random ID its not necessary for the user to manually set an ID
