### ISSUE TITLE
Can  I update the matrix to 8*40 

### ISSUE THREAD

**Issue by Laiwxn** [awtrix/AWTRIX2.0-Controller#23]
As the title.I want to update the matirx to 8*40,and use 3528 footprint to reduce the area of the PCB.
Thanks

**Comment by cattypapa** [comment]
Not active here.Disappointing.Hope more people pay attention to this project.

**Comment by Blueforcer** [comment]
In theory yes, but never tested it cause all apps are designed for 8x32

**Comment by Laiwxn** [comment]
That's the problem,got it.Thanks.
