### ISSUE TITLE
How can i change Host IP?

### ISSUE THREAD

**Issue by huwei1024** [awtrix/AWTRIX2.0-Controller#27]
How can i change Host IP?

**Comment by Chris-Hoo** [comment]
open src/AWTRIXController.cpp
change this variable: char awtrix_server[16] = "0.0.0.0";

**Comment by Blueforcer** [comment]
this wont work because the seetings will be loaded from the saved json.
Just reset the controller by double reset it by an interval of 4s

**Comment by huwei1024** [comment]
@Blueforcer ok. Thanks.
