### ISSUE TITLE
Time zone In settings not refresh in AWTRIX

### ISSUE THREAD

**Issue by cayetano** [awtrix/AWTRIX2.0-Controller#28]
First sorry, I have a bad english

Set the time zone in "settings->home" is not reflected in time display in AWTRIX.

Regards.
Cayetano

P.S. your work is amazing !!!!!

**Comment by cayetano** [comment]
Reboot wemos , then reboot host .... and "voila" al run perfectly.

Thanks !!!!!!!

Resolved !!!!

**Comment by GarfieldQAQ** [comment]
i cannot find timezone offset in setting...
i dont know why...
