### ISSUE TITLE
PCB available?

### ISSUE THREAD

**Issue by BlueAndi** [awtrix/AWTRIX2.0-Controller#3]
Will there be a PCB provided, containing all the sensors and etc.?

**Comment by Blueforcer** [comment]
Yes, its in development right now
![60071210_434413203958557_7973175604667219968_o](https://user-images.githubusercontent.com/31169771/57986872-98394680-7a7a-11e9-8c81-053bd41b34a9.jpg)

**Comment by BlueAndi** [comment]
Looks great. Can I see the schematic anywhere?
Is there a fuse and a supply reverse connect protection on it?
And the important question, when do you expect to release it? ;-)

**Comment by Mazze2000** [comment]
> Is there a fuse and a supply reverse connect protection on it?
Yes, it is ;-)

**Comment by BlueAndi** [comment]
Thanks Matthias for the reply. In the meantime I started with a PCB too, but based on an ESP32.
