### ISSUE TITLE
Can't conncet to host when the server port is five digits

### ISSUE THREAD

**Issue by Wannagift** [awtrix/AWTRIX2.0-Controller#34]
![批注 2020-08-21 123132](https://user-images.githubusercontent.com/70002582/90852621-84317280-e3aa-11ea-8de3-c861b169ff45.png)
![IMG_20200821_123203](https://user-images.githubusercontent.com/70002582/90852695-c3f85a00-e3aa-11ea-8d49-e339ddf0fb17.jpg)
![IMG_20200821_123217](https://user-images.githubusercontent.com/70002582/90852698-c6f34a80-e3aa-11ea-9579-cb5485137c91.jpg)
This is not friendly to people who have to use port mappings.  Hope to fix it.Thank you!

**Comment by Blueforcer** [comment]
Should be fixed in https://github.com/awtrix/AWTRIX2.0-Controller/commit/2c47ebe5c9a4e070ba1c1d012fbbec0c359b0081
