### ISSUE TITLE
AWTRIX HOST IP SET FAILED

### ISSUE THREAD

**Issue by AICrazy** [awtrix/AWTRIX2.0-Controller#37]
Hello,

Every time I configure wifi and HOST IP in this step, wifi ap can be set successfully, but HOST IP configuration fails, HOST IP is always the default value 0.0.0.0.

Thank you.

![24a1a8532b83a3831cf4f5c966b105b](https://user-images.githubusercontent.com/40334404/115986241-de41a200-a5e1-11eb-928f-586ad62be379.jpg)

**Comment by BornTKill** [comment]
@AICrazy Add same issue after upgrading. To fix I erase the esp and flash again with firmware download on documentation page. Good Luck

**Comment by jh163888** [comment]
Same issue here, but I have no access to USB-COM port any more since I 3D print the whole clock and left no debug port.. lol Waiting for the fix to upgrade through wifi.

**Comment by BattloXX** [comment]
I have the sam Problem with the update

**Comment by Blueforcer** [comment]
Yep, in some cases there are old files available from older flashed Programms. 
Erase the complete esp and you will be fine
