### ISSUE TITLE
Support for 44 x 11 matrix

### ISSUE THREAD

**Issue by kaikoops** [awtrix/AWTRIX2.0-Controller#42]
Hello,
i own a 44 x 11 (WS2812B based) led matrix. Is there any support for matrices (not tiled) other than the 32 x 8 ones?
Basically I would be fine with changing the code on my own. What is the preferred tool chain to build the firmware.bin?

Thx in advance and stay healthy.

**Comment by Blueforcer** [comment]
Sorry, awtrix only supports 32x8
