### ISSUE TITLE
Support for esp32 on platformio devices

### ISSUE THREAD

**Issue by diogopms** [awtrix/AWTRIX2.0-Controller#52]
https://github.com/awtrix/AWTRIX2.0-Controller/blob/master/platformio.ini#L23
To be easier to compile to multiple devices

**Comment by Blueforcer** [comment]
ESP32 and ESP8266 use vastly different approaches to handle the network. 8266 is single core, uses very low level LwIP API and can get away with it. ESP32 is dual-core, running on top of an actual OS. It's targets are not to be the fastest.

Therefor in my tests the ESP is much slower in handling the network messages and caused in heavy stuttering
